create table if not exists public.treasure_ratings (
  id bigint generated by default as identity primary key,
  treasure_id bigint not null references public.treasures(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  user_id uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists treasure_ratings_treasure_id_idx
on public.treasure_ratings(treasure_id);

alter table public.treasure_ratings enable row level security;
revoke all on table public.treasure_ratings from anon, authenticated;

create or replace function public.get_treasure_rating_summary(p_treasure_id bigint)
returns table (average_rating numeric, rating_count bigint)
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(round(avg(rating)::numeric, 1), 0) as average_rating,
    count(*) as rating_count
  from public.treasure_ratings
  where treasure_id = p_treasure_id;
$$;

create or replace function public.submit_treasure_rating(
  p_treasure_id bigint,
  p_rating smallint
)
returns table (average_rating numeric, rating_count bigint)
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_rating < 1 or p_rating > 5 then
    raise exception 'rating must be between 1 and 5';
  end if;

  insert into public.treasure_ratings (treasure_id, rating, user_id)
  values (p_treasure_id, p_rating, auth.uid());

  return query
  select
    coalesce(round(avg(tr.rating)::numeric, 1), 0) as average_rating,
    count(*) as rating_count
  from public.treasure_ratings tr
  where tr.treasure_id = p_treasure_id;
end;
$$;

revoke all on function public.get_treasure_rating_summary(bigint) from public;
revoke all on function public.submit_treasure_rating(bigint, smallint) from public;
grant execute on function public.get_treasure_rating_summary(bigint) to anon, authenticated;
grant execute on function public.submit_treasure_rating(bigint, smallint) to anon, authenticated;
